[test_settings.py]
[test_carrier_settings.py]
carrier = true
# Bug 850313 Cannot browse via the cellular network after manual flash Unagi
xfail = true
[test_wifi_settings.py]
wifi = true
